---
title: Animate a snow scene
hero_image: images/banner.png
description: Animate a car driving through a snow scene using Blender
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-03-01
steps:
- title: What you will make
- title: Where is the camera?
- title: Keyframing
  completion:
  - engaged
- title: Key frame the first frame
- title: Key frame the end frame
- title: Fine-tune the animation
  completion:
  - internal
- title: Challenge
  completion:
  - external
- title: What can you do now?
