---
title: बर्फ का दृश्य (drshy) एनिमेट करें
hero_image: images/banner.png
description: Blender का उपयोग करके बर्फ दृश्य में से कार चलाने को एनिमेट करें।
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-03-01
steps:
- title: परिचय
  completion: engaged
- title: कैमरा कहाँ है?
- title: मुख्य फ्रेम बनाना
- title: मुख्य फ्रेम पहला फ्रेम
- title: मुख्य फ्रेम अंतिम फ्रेम
- title: एनिमेशन फाइन-ट्यून करें
  completion: internal
- title: 'चुनौती: रॉकेट लॉन्च करें'
