---
title: Animate a snow scene
hero_image: imagens/banner.png
description: Animate a car driving through a snow scene using Blender
theme: blue #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: liquidificador
site_areas: projects
hardware: ''
software: liquidificador
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introdução
  - 
    title: O que você vai precisar
  - 
    title: Where is the camera?
  - 
    title: Keyframing
  - 
    title: Key frame the first frame
  - 
    title: Key frame the end frame
  - 
    title: Fine-tune the animation
  - 
    title: "Challenge: launch the rocket"
