---
title: Anima una escena en la nieve
hero_image: images/banner.png
description: Anima un auto que atraviesa una escena en la nieve usando Blender
theme: azul
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: weather, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-03-01
steps:
  - 
    title: Introducción
  - 
    title: '¿Dónde está la cámara?'
  - 
    title: Cuadros clave (o "Keyframing")
    completion:
      - engaged
  - 
    title: Crea el primer cuadro clave
  - 
    title: Crea el último cuadro clave
  - 
    title: Ajusta detalles en la animación
    completion:
      - internal
  - 
    title: 'Desafío: lanza el cohete'
